export const booleanColumns = ['asthma', 'dm', 'cvd', 'copd'];
export const excludedColumns = [
  'gender',
  'email',
  'gms',
  'regadte',
  'type',
  'hcp',
  'expdate',
  'cdm_condition_count',
  'potential_income',
  'accepted',
  'refused',
];

export const headerLabels: Record<string, string> = {
  name: 'Name',
  dob: 'D.O.B.',
  gender: 'Gender',
  address: 'Address',
  home_phone: 'Home Phone',
  mobile_phone: 'Mobile Phone',
  email: 'Email',
  gms: 'GMS',
  regdate: 'Registration Date',
  type: 'Type',
  hcp: 'HCP',
  expdate: 'Expiration Date',
  asthma: 'Asthma',
  dm: 'DM',
  cvd: 'CVD',
  copd: 'COPD',
  cdm_condition_count: 'CDM Condition Count',
  potential_income: 'Potential Income',
  accepted: 'Accepted',
  refused: 'Refused',
};
